### ISSUE TITLE
Allow custom CSS colors

### ISSUE THREAD

**Issue by BelkaDev** [benji300/joplin-note-tabs#47]
It appears that the color change event is hard-coded and cannot be altered manually, like for example:
```CSS
/* userchrome.css */
#tabs-container {
  background-color: --var(customColor) !important;
}
```
Can this be done differently?
